[package]
name = "kira"
version = "0.1.0"
authors = ["Andrew Minnich <aminnich3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cpal = "0.13.1"
flume = "0.10.1"
indexmap = "1.6.1"
lewton = "0.10.1"
